### ISSUE TITLE
Error handling for incorrect Troe reaction data

### ISSUE THREAD

**Issue by kahilah** [kyleniemeyer/pyJac#11]
Hey!

I noticed that e.g. for the DME mechanism available: http://www.engr.uconn.edu/~tlu/mechs/mechs.htm

( particularly: http://www.engr.uconn.edu/~tlu/mechs/DME.zip and the skeletal one)

one gets an error: 

-------------------------------------------------------------------------------------------------------------------------------
```
.
.
.
  File "/.../pyjac/core/create_jacobian.py", line 1175, in get_pdep_dt
    jline += write_troe_dt(lang, rxn, beta_0minf, E_0minf, k0kinf)
  File "/.../pyjac/core/create_jacobian.py", line 1274, in write_troe_dt
    rxn.troe_par[2]) +
ZeroDivisionError: float division by zero
```
-------------------------------------------------------------------------------------------------------------------------------

and this is due to a zero value in one of the troe parameters in the reaction file. When the zero is changed to 1e-30 as in others, pyjac creates the jacobian files without problems.

Not directly a problem on the pyjac side but maybe worth to consider a some sort of check-up routine and warning message for the user.

Cheers,
-HK

**Comment by arghdos** [comment]
@kahilah Thanks for the bug report!

Technically speaking, the reaction in that DME mechanism is undefined--it takes the form of 0 * exp(T / 0).  I am looking into how Cantera / chemkin handle this reaction in order to figure out what we should do

**Comment by kyleniemeyer** [comment]
@arghdos it sounds like this is the same as commenting out the reaction—so perhaps we should just skip reactions with a pre-exponential factor of 0?

**Comment by arghdos** [comment]
@kyleniemeyer thoughts?  I've brought this up on the [cantera github](https://github.com/Cantera/cantera/issues/404) as well

**Comment by arghdos** [comment]
@kyleniemeyer this particular reaction still has a non-zero Fcent as:

`Fcent = (1 - a) * exp(-T / T3) + a* exp(-T/ T1) + exp(-T2 / T)`

For this given reaction it simplifies to:

`Fcent = 1 * exp(-T / 570) + 0 * exp(-T / 0) + exp(-1e+30 / T)`

Hence we still have contributions from the leading term

**Comment by arghdos** [comment]
Handled by 7188be7, thanks again for the report!
